var projects = [{"id":"1",
"nomProjet":"Portrait Chinois",
"statusProjet": "BUT MMI",
"anneeProjet": "2022",
"typeProjet": "Développement Web",
 "usedLanguages":"HTML, CSS, JS",
 "img":'projectsImg/portrait-chinois-2022.png', "class":'img-prjt',
  "nomParticipant1":"Andy Rabarison",
    "desc":"Premier projet de développement web réaliser en BUT MMI. Le but du site était de se présenter par 7 analogies qui représente certains trait de notre personnalité/qui possèdent une place importante dans notre vie. Il s'agit du premier grand pas dans le développement web et d'une utilisation plus complexe de JavaScript.",
    "link":"https://rabarison-andy.github.io/Portrait-chinois/",
    "responvie":"❌",},

{"id":"2",
  "nomProjet":"Mini-Blog",
  "statusProjet": "BUT MMI",
  "anneeProjet": "2023",
  "typeProjet": "Développement Web",
   "usedLanguages":"HTML, CSS, JS, PHP, MySQL",
   "img":'projectsImg/W.I.P.png', "class":'img-prjt',
    "nomParticipant1":"Andy Rabarison,https://rabarison-andy.github.io/",
    "desc":"Developpement d'un mini blog, avec possibilité de commenté, de poster des articles et de les consultés même si l'on n'est pas connecté. Premier projet ou l'architecture MVC (Modèle-Vue-Contrôleur) à été vus et imposer sur l'arborescence du site. Site dont il est possible de voir les publications récentes, de se connecter/s'inscrire et de pouvoir commenter les publications.",
    "link":"STILL WORKING ON IT",
    "responvie":"❌",},

{"id":"3",
    "nomProjet":"Resaweb",
    "statusProjet": "BUT MMI",
    "anneeProjet": "2023",
    "typeProjet": "Développement Web",
     "usedLanguages":"HTML, CSS, JS, PHP, MySQL",
     "img":'projectsImg/resaweb_2023.png', "class":'img-prjt',
      "nomParticipant1":"Andy Rabarison,https://rabarison-andy.github.io/",
        "desc":"Site de reservation coder en PHP, le but était de créer un site de reservation sur un produit ou un service, ici il s'agit d'un site de reservation de pc portable pour étudiant. Plusieurs fonctionnalité on été faites sur le site comme l'envoi d'un mail personnalisé lors de la reservation d'un produit, l'affichage automatique des derniers produits introduits dans la base de données mais aussi un filtre en PHP pour afficher les produits selon une certaines manière.",
        "link":"https://resaweb.rabarison.butmmi.o2switch.site",
        "responvie":"✔️ (1193px~694px)"},

{"id":"4",
    "nomProjet":"EnerViz'",
    "statusProjet": "BUT MMI",
    "anneeProjet": "2023",
    "typeProjet": "Développement Web",
    "usedLanguages":"HTML, CSS, JS, SPLINE, Chart.js, Git",
    "img":'projectsImg/EnerViz_2023.png', "class":'img-prjt',
    "nomParticipant1":"Dan Phan Nguyen,https://danpn.eu",
    "nomParticipant2":"Andy Rabarison,https://rabarison-andy.github.io/",
    "nomParticipant3":"Léana Lim,https://leanalim.github.io/",
    "desc":"Premier projet de développement web réaliser en tant que deuxième année de BUT MMI. Realiser en équipe de trois, nous avions eu pour ambitions dès le début d'utiliser de la 3d pour ce site, et pour pouvoir directement commencer le développement sans perdre de temps nous avons utiliser l'outil SPLINE pour créer la map 3d et gérer les intéractions. Quelques difficultés ont été rencontré du fait que l'outil étant très récent, la documention n'est pas très fournit et personne n'a eu d'utilisation de l'outil comme nous, il a donc fallut explorer à l'aveugle l'utilisation de cette outil mais pour avoir un rendu incroyable au final.",
    "link":"https://leanalim.github.io/EnerViz/",
    "responvie":"❌"},

{"id":"5",
    "nomProjet":"CV Vidéo",
    "statusProjet": "BUT MMI",
    "anneeProjet": "2023",
    "typeProjet": "Montage Vidéo",
    "usedLanguages":"Adobe Premiere Pro, Adobe After Effect, Adobe Photoshop, Alight Motion",
    "img":'projectsImg/W.I.P.png', "class":'img-prjt',
    "nomParticipant1":"Andy Rabarison,https://rabarison-andy.github.io/",
    "nomParticipant2":"Enzo Fortes,https://enzofortes.github.io/",
    "desc":"CV Vidéo réaliser dans le cadre d'un projet MMI, servant à se présenter, à se mettre en avant et d'avoir une approche différente du CV  original. Cela m'a permis de plus me plonger dans les techniques de traking mais surtout dans le domaine du motion design qui m'interesse grandement.",
    "link":"STILL WORKING ON IT",},

    {"id":"6",
    "nomProjet":"Recyclick",
    "anneeProjet": "2022",
    "statusProjet": "BUT Informatique",
    "typeProjet": "Développement Web",
    "usedLanguages":"HTML, CSS, JS, PHP, MySQL, Git",
    "img":'projectsImg/Recyclick_2022.png', "class":'img-prjt',
    "nomParticipant1":"Simon Catanese,",
    "nomParticipant2":"Tom Delavigne,",
    "nomParticipant3":"Andy Rabarison,https://rabarison-andy.github.io/",
    "desc":"Site réaliser durant mon BUT INFO (avant mon arrivé en BUT MMI), notre but est de créer un site internet reprenant le principe de boutique en ligne. Notre but est de promouvoir l'économie circulaire.Pour cela, le client à la possibilité de vendre et d'acheter des produits électroniques. À chaque revente, la récompense est que le prix s'additionne dans une cagnotte. Ce qui lui permettra lors d'un achat de déduire sur le prix des produits.",
    "link":"https://dwarves.iut-fbleau.fr/~catanese/SAEDEV/BUT1-SAE-2.02-catanese-delavigne-rabarison/vues/index.php",
    "responvie":"❌"}];